# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

name: $(Version.MajorMinor)$(Rev:.r)

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Version.MajorMinor: 1.0.0

steps:
- task: NuGetToolInstaller@0

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'nuget.exe sources Add -Name "xboxftp" -Source "https://nrjsolutions.pkgs.visualstudio.com/_packaging/xboxftp/nuget/v3/index.json"'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    zipAfterPublish: true
    majorVersion: 1
    minorVersion: 0
    patchVersion: 0
    publishWebProjects: false
    arguments: --runtime win-x86